[package]
name = "ajazz-rs"
description = "HidApi driver for Ajazz devices"
authors = ["TheJebForge"]
version = "0.10.2"
edition = "2021"
readme = "README.md"
homepage = "https://github.com/streamduck-org"
repository = "https://github.com/streamduck-org/ajazz"
license = "MPL-2.0"

[dependencies]
hidapi = "2.6"
image = { version = "0.25.5", default-features = false, features = [
  "bmp",
  "jpeg",
] }
tokio = { version = "1", optional = true }

[features]
async = [
  "tokio",
  "tokio/sync",
  "tokio/rt-multi-thread",
  "tokio/time"
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
