[package]
name = "screen_mirroring"
edition = "2021"
publish = false

[dependencies]
image = { version = "0.25.1", default-features = false, features = ["bmp", "jpeg"] }
ajazz-sdk = { path = "../../"}
scap = "0.0.8"
rustyline = "14.0"
